# CMake generated Testfile for 
# Source directory: C:/Users/Woazim/source/repos/glshaderpp/test
# Build directory: C:/Users/Woazim/source/repos/glshaderpp/testbuild/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(direct-shader-from-files "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug/testProg.exe" "[direct-shader-from-files]")
  set_tests_properties(direct-shader-from-files PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;74;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(direct-shader-from-files "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release/testProg.exe" "[direct-shader-from-files]")
  set_tests_properties(direct-shader-from-files PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;74;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(direct-shader-from-files "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel/testProg.exe" "[direct-shader-from-files]")
  set_tests_properties(direct-shader-from-files PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;74;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(direct-shader-from-files "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo/testProg.exe" "[direct-shader-from-files]")
  set_tests_properties(direct-shader-from-files PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;74;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
else()
  add_test(direct-shader-from-files NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(shader-from-files "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug/testProg.exe" "[shader-from-files]")
  set_tests_properties(shader-from-files PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;75;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(shader-from-files "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release/testProg.exe" "[shader-from-files]")
  set_tests_properties(shader-from-files PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;75;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(shader-from-files "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel/testProg.exe" "[shader-from-files]")
  set_tests_properties(shader-from-files PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;75;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(shader-from-files "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo/testProg.exe" "[shader-from-files]")
  set_tests_properties(shader-from-files PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;75;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
else()
  add_test(shader-from-files NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(direct-shader-from-strings "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug/testProg.exe" "[direct-shader-from-strings]")
  set_tests_properties(direct-shader-from-strings PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;76;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(direct-shader-from-strings "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release/testProg.exe" "[direct-shader-from-strings]")
  set_tests_properties(direct-shader-from-strings PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;76;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(direct-shader-from-strings "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel/testProg.exe" "[direct-shader-from-strings]")
  set_tests_properties(direct-shader-from-strings PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;76;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(direct-shader-from-strings "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo/testProg.exe" "[direct-shader-from-strings]")
  set_tests_properties(direct-shader-from-strings PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;76;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
else()
  add_test(direct-shader-from-strings NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(direct-vertex-from-files "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug/testProg.exe" "[direct-vertex-from-files]")
  set_tests_properties(direct-vertex-from-files PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;77;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(direct-vertex-from-files "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release/testProg.exe" "[direct-vertex-from-files]")
  set_tests_properties(direct-vertex-from-files PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;77;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(direct-vertex-from-files "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel/testProg.exe" "[direct-vertex-from-files]")
  set_tests_properties(direct-vertex-from-files PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;77;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(direct-vertex-from-files "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo/testProg.exe" "[direct-vertex-from-files]")
  set_tests_properties(direct-vertex-from-files PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;77;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
else()
  add_test(direct-vertex-from-files NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(direct-fragment-from-files "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug/testProg.exe" "[direct-fragment-from-files]")
  set_tests_properties(direct-fragment-from-files PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;78;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(direct-fragment-from-files "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release/testProg.exe" "[direct-fragment-from-files]")
  set_tests_properties(direct-fragment-from-files PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;78;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(direct-fragment-from-files "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel/testProg.exe" "[direct-fragment-from-files]")
  set_tests_properties(direct-fragment-from-files PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;78;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(direct-fragment-from-files "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo/testProg.exe" "[direct-fragment-from-files]")
  set_tests_properties(direct-fragment-from-files PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;78;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
else()
  add_test(direct-fragment-from-files NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(vertex-from-files "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug/testProg.exe" "[vertex-from-files]")
  set_tests_properties(vertex-from-files PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;79;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(vertex-from-files "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release/testProg.exe" "[vertex-from-files]")
  set_tests_properties(vertex-from-files PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;79;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(vertex-from-files "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel/testProg.exe" "[vertex-from-files]")
  set_tests_properties(vertex-from-files PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;79;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(vertex-from-files "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo/testProg.exe" "[vertex-from-files]")
  set_tests_properties(vertex-from-files PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;79;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
else()
  add_test(vertex-from-files NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(fragment-from-files "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug/testProg.exe" "[fragment-from-files]")
  set_tests_properties(fragment-from-files PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;80;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(fragment-from-files "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release/testProg.exe" "[fragment-from-files]")
  set_tests_properties(fragment-from-files PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;80;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(fragment-from-files "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel/testProg.exe" "[fragment-from-files]")
  set_tests_properties(fragment-from-files PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;80;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(fragment-from-files "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo/testProg.exe" "[fragment-from-files]")
  set_tests_properties(fragment-from-files PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;80;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
else()
  add_test(fragment-from-files NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(direct-faulty-vertex "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug/testProg.exe" "[direct-faulty-vertex]")
  set_tests_properties(direct-faulty-vertex PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;81;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(direct-faulty-vertex "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release/testProg.exe" "[direct-faulty-vertex]")
  set_tests_properties(direct-faulty-vertex PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;81;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(direct-faulty-vertex "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel/testProg.exe" "[direct-faulty-vertex]")
  set_tests_properties(direct-faulty-vertex PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;81;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(direct-faulty-vertex "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo/testProg.exe" "[direct-faulty-vertex]")
  set_tests_properties(direct-faulty-vertex PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;81;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
else()
  add_test(direct-faulty-vertex NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(faulty-vertex "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug/testProg.exe" "[faulty-vertex]")
  set_tests_properties(faulty-vertex PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;82;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(faulty-vertex "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release/testProg.exe" "[faulty-vertex]")
  set_tests_properties(faulty-vertex PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;82;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(faulty-vertex "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel/testProg.exe" "[faulty-vertex]")
  set_tests_properties(faulty-vertex PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;82;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(faulty-vertex "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo/testProg.exe" "[faulty-vertex]")
  set_tests_properties(faulty-vertex PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;82;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
else()
  add_test(faulty-vertex NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(direct-notready-program "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug/testProg.exe" "[direct-notready-program]")
  set_tests_properties(direct-notready-program PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;83;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(direct-notready-program "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release/testProg.exe" "[direct-notready-program]")
  set_tests_properties(direct-notready-program PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;83;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(direct-notready-program "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel/testProg.exe" "[direct-notready-program]")
  set_tests_properties(direct-notready-program PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;83;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(direct-notready-program "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo/testProg.exe" "[direct-notready-program]")
  set_tests_properties(direct-notready-program PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;83;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
else()
  add_test(direct-notready-program NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(notready-program "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug/testProg.exe" "[notready-program]")
  set_tests_properties(notready-program PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;84;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(notready-program "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release/testProg.exe" "[notready-program]")
  set_tests_properties(notready-program PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;84;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(notready-program "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel/testProg.exe" "[notready-program]")
  set_tests_properties(notready-program PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;84;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(notready-program "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo/testProg.exe" "[notready-program]")
  set_tests_properties(notready-program PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;84;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
else()
  add_test(notready-program NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(direct-faulty-program "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug/testProg.exe" "[direct-faulty-program]")
  set_tests_properties(direct-faulty-program PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;85;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(direct-faulty-program "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release/testProg.exe" "[direct-faulty-program]")
  set_tests_properties(direct-faulty-program PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;85;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(direct-faulty-program "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel/testProg.exe" "[direct-faulty-program]")
  set_tests_properties(direct-faulty-program PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;85;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(direct-faulty-program "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo/testProg.exe" "[direct-faulty-program]")
  set_tests_properties(direct-faulty-program PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;85;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
else()
  add_test(direct-faulty-program NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(faulty-program "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug/testProg.exe" "[faulty-program]")
  set_tests_properties(faulty-program PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;86;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(faulty-program "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release/testProg.exe" "[faulty-program]")
  set_tests_properties(faulty-program PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;86;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(faulty-program "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel/testProg.exe" "[faulty-program]")
  set_tests_properties(faulty-program PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;86;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(faulty-program "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo/testProg.exe" "[faulty-program]")
  set_tests_properties(faulty-program PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;86;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
else()
  add_test(faulty-program NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bad-source-stream "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug/testProg.exe" "[bad-source-stream]")
  set_tests_properties(bad-source-stream PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;87;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bad-source-stream "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release/testProg.exe" "[bad-source-stream]")
  set_tests_properties(bad-source-stream PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;87;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bad-source-stream "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel/testProg.exe" "[bad-source-stream]")
  set_tests_properties(bad-source-stream PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;87;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bad-source-stream "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo/testProg.exe" "[bad-source-stream]")
  set_tests_properties(bad-source-stream PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;87;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
else()
  add_test(bad-source-stream NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(no-glewinit "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug/testProg.exe" "[no-glewinit]")
  set_tests_properties(no-glewinit PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Debug" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;88;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(no-glewinit "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release/testProg.exe" "[no-glewinit]")
  set_tests_properties(no-glewinit PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/Release" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;88;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(no-glewinit "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel/testProg.exe" "[no-glewinit]")
  set_tests_properties(no-glewinit PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/MinSizeRel" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;88;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(no-glewinit "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo/testProg.exe" "[no-glewinit]")
  set_tests_properties(no-glewinit PROPERTIES  WORKING_DIRECTORY "C:/Users/Woazim/source/repos/glshaderpp/testbuild/test/RelWithDebInfo" _BACKTRACE_TRIPLES "C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;88;add_test;C:/Users/Woazim/source/repos/glshaderpp/test/CMakeLists.txt;0;")
else()
  add_test(no-glewinit NOT_AVAILABLE)
endif()
