
#################
###  GLEW
#################
set(CONAN_GLEW_ROOT_RELEASE "C:/Users/Woazim/.conan/data/glew/2.2.0/_/_/package/f923874e83d95e94b1d71b4181e264b3716ade72")
set(CONAN_INCLUDE_DIRS_GLEW_RELEASE "C:/Users/Woazim/.conan/data/glew/2.2.0/_/_/package/f923874e83d95e94b1d71b4181e264b3716ade72/include")
set(CONAN_LIB_DIRS_GLEW_RELEASE "C:/Users/Woazim/.conan/data/glew/2.2.0/_/_/package/f923874e83d95e94b1d71b4181e264b3716ade72/lib")
set(CONAN_BIN_DIRS_GLEW_RELEASE )
set(CONAN_RES_DIRS_GLEW_RELEASE )
set(CONAN_SRC_DIRS_GLEW_RELEASE )
set(CONAN_BUILD_DIRS_GLEW_RELEASE "C:/Users/Woazim/.conan/data/glew/2.2.0/_/_/package/f923874e83d95e94b1d71b4181e264b3716ade72/")
set(CONAN_FRAMEWORK_DIRS_GLEW_RELEASE )
set(CONAN_LIBS_GLEW_RELEASE libglew32)
set(CONAN_PKG_LIBS_GLEW_RELEASE libglew32)
set(CONAN_SYSTEM_LIBS_GLEW_RELEASE )
set(CONAN_FRAMEWORKS_GLEW_RELEASE )
set(CONAN_FRAMEWORKS_FOUND_GLEW_RELEASE "")  # Will be filled later
set(CONAN_DEFINES_GLEW_RELEASE "-DGLEW_STATIC")
set(CONAN_BUILD_MODULES_PATHS_GLEW_RELEASE )
# COMPILE_DEFINITIONS are equal to CONAN_DEFINES without -D, for targets
set(CONAN_COMPILE_DEFINITIONS_GLEW_RELEASE "GLEW_STATIC")

set(CONAN_C_FLAGS_GLEW_RELEASE "")
set(CONAN_CXX_FLAGS_GLEW_RELEASE "")
set(CONAN_SHARED_LINKER_FLAGS_GLEW_RELEASE "")
set(CONAN_EXE_LINKER_FLAGS_GLEW_RELEASE "")

# For modern cmake targets we use the list variables (separated with ;)
set(CONAN_C_FLAGS_GLEW_RELEASE_LIST "")
set(CONAN_CXX_FLAGS_GLEW_RELEASE_LIST "")
set(CONAN_SHARED_LINKER_FLAGS_GLEW_RELEASE_LIST "")
set(CONAN_EXE_LINKER_FLAGS_GLEW_RELEASE_LIST "")

# Apple Frameworks
conan_find_apple_frameworks(CONAN_FRAMEWORKS_FOUND_GLEW_RELEASE "${CONAN_FRAMEWORKS_GLEW_RELEASE}" "_GLEW" "_RELEASE")
# Append to aggregated values variable
set(CONAN_LIBS_GLEW_RELEASE ${CONAN_PKG_LIBS_GLEW_RELEASE} ${CONAN_SYSTEM_LIBS_GLEW_RELEASE} ${CONAN_FRAMEWORKS_FOUND_GLEW_RELEASE})


#################
###  GLFW
#################
set(CONAN_GLFW_ROOT_RELEASE "C:/Users/Woazim/.conan/data/glfw/3.3.7/_/_/package/d3cffeefc8c8bcb6be8abdd182cb1b56fc81bacc")
set(CONAN_INCLUDE_DIRS_GLFW_RELEASE "C:/Users/Woazim/.conan/data/glfw/3.3.7/_/_/package/d3cffeefc8c8bcb6be8abdd182cb1b56fc81bacc/include")
set(CONAN_LIB_DIRS_GLFW_RELEASE "C:/Users/Woazim/.conan/data/glfw/3.3.7/_/_/package/d3cffeefc8c8bcb6be8abdd182cb1b56fc81bacc/lib")
set(CONAN_BIN_DIRS_GLFW_RELEASE )
set(CONAN_RES_DIRS_GLFW_RELEASE )
set(CONAN_SRC_DIRS_GLFW_RELEASE )
set(CONAN_BUILD_DIRS_GLFW_RELEASE "C:/Users/Woazim/.conan/data/glfw/3.3.7/_/_/package/d3cffeefc8c8bcb6be8abdd182cb1b56fc81bacc/")
set(CONAN_FRAMEWORK_DIRS_GLFW_RELEASE )
set(CONAN_LIBS_GLFW_RELEASE glfw3)
set(CONAN_PKG_LIBS_GLFW_RELEASE glfw3)
set(CONAN_SYSTEM_LIBS_GLFW_RELEASE gdi32)
set(CONAN_FRAMEWORKS_GLFW_RELEASE )
set(CONAN_FRAMEWORKS_FOUND_GLFW_RELEASE "")  # Will be filled later
set(CONAN_DEFINES_GLFW_RELEASE )
set(CONAN_BUILD_MODULES_PATHS_GLFW_RELEASE )
# COMPILE_DEFINITIONS are equal to CONAN_DEFINES without -D, for targets
set(CONAN_COMPILE_DEFINITIONS_GLFW_RELEASE )

set(CONAN_C_FLAGS_GLFW_RELEASE "")
set(CONAN_CXX_FLAGS_GLFW_RELEASE "")
set(CONAN_SHARED_LINKER_FLAGS_GLFW_RELEASE "")
set(CONAN_EXE_LINKER_FLAGS_GLFW_RELEASE "")

# For modern cmake targets we use the list variables (separated with ;)
set(CONAN_C_FLAGS_GLFW_RELEASE_LIST "")
set(CONAN_CXX_FLAGS_GLFW_RELEASE_LIST "")
set(CONAN_SHARED_LINKER_FLAGS_GLFW_RELEASE_LIST "")
set(CONAN_EXE_LINKER_FLAGS_GLFW_RELEASE_LIST "")

# Apple Frameworks
conan_find_apple_frameworks(CONAN_FRAMEWORKS_FOUND_GLFW_RELEASE "${CONAN_FRAMEWORKS_GLFW_RELEASE}" "_GLFW" "_RELEASE")
# Append to aggregated values variable
set(CONAN_LIBS_GLFW_RELEASE ${CONAN_PKG_LIBS_GLFW_RELEASE} ${CONAN_SYSTEM_LIBS_GLFW_RELEASE} ${CONAN_FRAMEWORKS_FOUND_GLFW_RELEASE})


#################
###  CATCH2
#################
set(CONAN_CATCH2_ROOT_RELEASE "C:/Users/Woazim/.conan/data/catch2/2.13.8/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9")
set(CONAN_INCLUDE_DIRS_CATCH2_RELEASE "C:/Users/Woazim/.conan/data/catch2/2.13.8/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include")
set(CONAN_LIB_DIRS_CATCH2_RELEASE "C:/Users/Woazim/.conan/data/catch2/2.13.8/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib")
set(CONAN_BIN_DIRS_CATCH2_RELEASE )
set(CONAN_RES_DIRS_CATCH2_RELEASE )
set(CONAN_SRC_DIRS_CATCH2_RELEASE )
set(CONAN_BUILD_DIRS_CATCH2_RELEASE "C:/Users/Woazim/.conan/data/catch2/2.13.8/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib/cmake/Catch2")
set(CONAN_FRAMEWORK_DIRS_CATCH2_RELEASE )
set(CONAN_LIBS_CATCH2_RELEASE )
set(CONAN_PKG_LIBS_CATCH2_RELEASE )
set(CONAN_SYSTEM_LIBS_CATCH2_RELEASE )
set(CONAN_FRAMEWORKS_CATCH2_RELEASE )
set(CONAN_FRAMEWORKS_FOUND_CATCH2_RELEASE "")  # Will be filled later
set(CONAN_DEFINES_CATCH2_RELEASE )
set(CONAN_BUILD_MODULES_PATHS_CATCH2_RELEASE )
# COMPILE_DEFINITIONS are equal to CONAN_DEFINES without -D, for targets
set(CONAN_COMPILE_DEFINITIONS_CATCH2_RELEASE )

set(CONAN_C_FLAGS_CATCH2_RELEASE "")
set(CONAN_CXX_FLAGS_CATCH2_RELEASE "")
set(CONAN_SHARED_LINKER_FLAGS_CATCH2_RELEASE "")
set(CONAN_EXE_LINKER_FLAGS_CATCH2_RELEASE "")

# For modern cmake targets we use the list variables (separated with ;)
set(CONAN_C_FLAGS_CATCH2_RELEASE_LIST "")
set(CONAN_CXX_FLAGS_CATCH2_RELEASE_LIST "")
set(CONAN_SHARED_LINKER_FLAGS_CATCH2_RELEASE_LIST "")
set(CONAN_EXE_LINKER_FLAGS_CATCH2_RELEASE_LIST "")

# Apple Frameworks
conan_find_apple_frameworks(CONAN_FRAMEWORKS_FOUND_CATCH2_RELEASE "${CONAN_FRAMEWORKS_CATCH2_RELEASE}" "_CATCH2" "_RELEASE")
# Append to aggregated values variable
set(CONAN_LIBS_CATCH2_RELEASE ${CONAN_PKG_LIBS_CATCH2_RELEASE} ${CONAN_SYSTEM_LIBS_CATCH2_RELEASE} ${CONAN_FRAMEWORKS_FOUND_CATCH2_RELEASE})


#################
###  GLU
#################
set(CONAN_GLU_ROOT_RELEASE "C:/Users/Woazim/.conan/data/glu/system/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9")
set(CONAN_INCLUDE_DIRS_GLU_RELEASE )
set(CONAN_LIB_DIRS_GLU_RELEASE )
set(CONAN_BIN_DIRS_GLU_RELEASE )
set(CONAN_RES_DIRS_GLU_RELEASE )
set(CONAN_SRC_DIRS_GLU_RELEASE )
set(CONAN_BUILD_DIRS_GLU_RELEASE "C:/Users/Woazim/.conan/data/glu/system/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/")
set(CONAN_FRAMEWORK_DIRS_GLU_RELEASE )
set(CONAN_LIBS_GLU_RELEASE )
set(CONAN_PKG_LIBS_GLU_RELEASE )
set(CONAN_SYSTEM_LIBS_GLU_RELEASE Glu32)
set(CONAN_FRAMEWORKS_GLU_RELEASE )
set(CONAN_FRAMEWORKS_FOUND_GLU_RELEASE "")  # Will be filled later
set(CONAN_DEFINES_GLU_RELEASE )
set(CONAN_BUILD_MODULES_PATHS_GLU_RELEASE )
# COMPILE_DEFINITIONS are equal to CONAN_DEFINES without -D, for targets
set(CONAN_COMPILE_DEFINITIONS_GLU_RELEASE )

set(CONAN_C_FLAGS_GLU_RELEASE "")
set(CONAN_CXX_FLAGS_GLU_RELEASE "")
set(CONAN_SHARED_LINKER_FLAGS_GLU_RELEASE "")
set(CONAN_EXE_LINKER_FLAGS_GLU_RELEASE "")

# For modern cmake targets we use the list variables (separated with ;)
set(CONAN_C_FLAGS_GLU_RELEASE_LIST "")
set(CONAN_CXX_FLAGS_GLU_RELEASE_LIST "")
set(CONAN_SHARED_LINKER_FLAGS_GLU_RELEASE_LIST "")
set(CONAN_EXE_LINKER_FLAGS_GLU_RELEASE_LIST "")

# Apple Frameworks
conan_find_apple_frameworks(CONAN_FRAMEWORKS_FOUND_GLU_RELEASE "${CONAN_FRAMEWORKS_GLU_RELEASE}" "_GLU" "_RELEASE")
# Append to aggregated values variable
set(CONAN_LIBS_GLU_RELEASE ${CONAN_PKG_LIBS_GLU_RELEASE} ${CONAN_SYSTEM_LIBS_GLU_RELEASE} ${CONAN_FRAMEWORKS_FOUND_GLU_RELEASE})


#################
###  OPENGL
#################
set(CONAN_OPENGL_ROOT_RELEASE "C:/Users/Woazim/.conan/data/opengl/system/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9")
set(CONAN_INCLUDE_DIRS_OPENGL_RELEASE )
set(CONAN_LIB_DIRS_OPENGL_RELEASE )
set(CONAN_BIN_DIRS_OPENGL_RELEASE )
set(CONAN_RES_DIRS_OPENGL_RELEASE )
set(CONAN_SRC_DIRS_OPENGL_RELEASE )
set(CONAN_BUILD_DIRS_OPENGL_RELEASE "C:/Users/Woazim/.conan/data/opengl/system/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/")
set(CONAN_FRAMEWORK_DIRS_OPENGL_RELEASE )
set(CONAN_LIBS_OPENGL_RELEASE )
set(CONAN_PKG_LIBS_OPENGL_RELEASE )
set(CONAN_SYSTEM_LIBS_OPENGL_RELEASE opengl32)
set(CONAN_FRAMEWORKS_OPENGL_RELEASE )
set(CONAN_FRAMEWORKS_FOUND_OPENGL_RELEASE "")  # Will be filled later
set(CONAN_DEFINES_OPENGL_RELEASE )
set(CONAN_BUILD_MODULES_PATHS_OPENGL_RELEASE )
# COMPILE_DEFINITIONS are equal to CONAN_DEFINES without -D, for targets
set(CONAN_COMPILE_DEFINITIONS_OPENGL_RELEASE )

set(CONAN_C_FLAGS_OPENGL_RELEASE "")
set(CONAN_CXX_FLAGS_OPENGL_RELEASE "")
set(CONAN_SHARED_LINKER_FLAGS_OPENGL_RELEASE "")
set(CONAN_EXE_LINKER_FLAGS_OPENGL_RELEASE "")

# For modern cmake targets we use the list variables (separated with ;)
set(CONAN_C_FLAGS_OPENGL_RELEASE_LIST "")
set(CONAN_CXX_FLAGS_OPENGL_RELEASE_LIST "")
set(CONAN_SHARED_LINKER_FLAGS_OPENGL_RELEASE_LIST "")
set(CONAN_EXE_LINKER_FLAGS_OPENGL_RELEASE_LIST "")

# Apple Frameworks
conan_find_apple_frameworks(CONAN_FRAMEWORKS_FOUND_OPENGL_RELEASE "${CONAN_FRAMEWORKS_OPENGL_RELEASE}" "_OPENGL" "_RELEASE")
# Append to aggregated values variable
set(CONAN_LIBS_OPENGL_RELEASE ${CONAN_PKG_LIBS_OPENGL_RELEASE} ${CONAN_SYSTEM_LIBS_OPENGL_RELEASE} ${CONAN_FRAMEWORKS_FOUND_OPENGL_RELEASE})


### Definition of global aggregated variables ###

set(CONAN_DEPENDENCIES_RELEASE glew glfw catch2 glu opengl)

set(CONAN_INCLUDE_DIRS_RELEASE "C:/Users/Woazim/.conan/data/glew/2.2.0/_/_/package/f923874e83d95e94b1d71b4181e264b3716ade72/include"
			"C:/Users/Woazim/.conan/data/glfw/3.3.7/_/_/package/d3cffeefc8c8bcb6be8abdd182cb1b56fc81bacc/include"
			"C:/Users/Woazim/.conan/data/catch2/2.13.8/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include" ${CONAN_INCLUDE_DIRS_RELEASE})
set(CONAN_LIB_DIRS_RELEASE "C:/Users/Woazim/.conan/data/glew/2.2.0/_/_/package/f923874e83d95e94b1d71b4181e264b3716ade72/lib"
			"C:/Users/Woazim/.conan/data/glfw/3.3.7/_/_/package/d3cffeefc8c8bcb6be8abdd182cb1b56fc81bacc/lib"
			"C:/Users/Woazim/.conan/data/catch2/2.13.8/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib" ${CONAN_LIB_DIRS_RELEASE})
set(CONAN_BIN_DIRS_RELEASE  ${CONAN_BIN_DIRS_RELEASE})
set(CONAN_RES_DIRS_RELEASE  ${CONAN_RES_DIRS_RELEASE})
set(CONAN_FRAMEWORK_DIRS_RELEASE  ${CONAN_FRAMEWORK_DIRS_RELEASE})
set(CONAN_LIBS_RELEASE libglew32 glfw3 ${CONAN_LIBS_RELEASE})
set(CONAN_PKG_LIBS_RELEASE libglew32 glfw3 ${CONAN_PKG_LIBS_RELEASE})
set(CONAN_SYSTEM_LIBS_RELEASE gdi32 Glu32 opengl32 ${CONAN_SYSTEM_LIBS_RELEASE})
set(CONAN_FRAMEWORKS_RELEASE  ${CONAN_FRAMEWORKS_RELEASE})
set(CONAN_FRAMEWORKS_FOUND_RELEASE "")  # Will be filled later
set(CONAN_DEFINES_RELEASE "-DGLEW_STATIC" ${CONAN_DEFINES_RELEASE})
set(CONAN_BUILD_MODULES_PATHS_RELEASE  ${CONAN_BUILD_MODULES_PATHS_RELEASE})
set(CONAN_CMAKE_MODULE_PATH_RELEASE "C:/Users/Woazim/.conan/data/glew/2.2.0/_/_/package/f923874e83d95e94b1d71b4181e264b3716ade72/"
			"C:/Users/Woazim/.conan/data/glfw/3.3.7/_/_/package/d3cffeefc8c8bcb6be8abdd182cb1b56fc81bacc/"
			"C:/Users/Woazim/.conan/data/catch2/2.13.8/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib/cmake/Catch2"
			"C:/Users/Woazim/.conan/data/glu/system/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/"
			"C:/Users/Woazim/.conan/data/opengl/system/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/" ${CONAN_CMAKE_MODULE_PATH_RELEASE})

set(CONAN_CXX_FLAGS_RELEASE " ${CONAN_CXX_FLAGS_RELEASE}")
set(CONAN_SHARED_LINKER_FLAGS_RELEASE " ${CONAN_SHARED_LINKER_FLAGS_RELEASE}")
set(CONAN_EXE_LINKER_FLAGS_RELEASE " ${CONAN_EXE_LINKER_FLAGS_RELEASE}")
set(CONAN_C_FLAGS_RELEASE " ${CONAN_C_FLAGS_RELEASE}")

# Apple Frameworks
conan_find_apple_frameworks(CONAN_FRAMEWORKS_FOUND_RELEASE "${CONAN_FRAMEWORKS_RELEASE}" "" "_RELEASE")
# Append to aggregated values variable: Use CONAN_LIBS instead of CONAN_PKG_LIBS to include user appended vars
set(CONAN_LIBS_RELEASE ${CONAN_LIBS_RELEASE} ${CONAN_SYSTEM_LIBS_RELEASE} ${CONAN_FRAMEWORKS_FOUND_RELEASE})
