
#################
###  GLEW
#################
set(CONAN_GLEW_ROOT_DEBUG "C:/Users/Woazim/.conan/data/glew/2.2.0/_/_/package/2cd10aa7b17419a389740c9a9a85afec1178e5cf")
set(CONAN_INCLUDE_DIRS_GLEW_DEBUG "C:/Users/Woazim/.conan/data/glew/2.2.0/_/_/package/2cd10aa7b17419a389740c9a9a85afec1178e5cf/include")
set(CONAN_LIB_DIRS_GLEW_DEBUG "C:/Users/Woazim/.conan/data/glew/2.2.0/_/_/package/2cd10aa7b17419a389740c9a9a85afec1178e5cf/lib")
set(CONAN_BIN_DIRS_GLEW_DEBUG )
set(CONAN_RES_DIRS_GLEW_DEBUG )
set(CONAN_SRC_DIRS_GLEW_DEBUG )
set(CONAN_BUILD_DIRS_GLEW_DEBUG "C:/Users/Woazim/.conan/data/glew/2.2.0/_/_/package/2cd10aa7b17419a389740c9a9a85afec1178e5cf/")
set(CONAN_FRAMEWORK_DIRS_GLEW_DEBUG )
set(CONAN_LIBS_GLEW_DEBUG libglew32d)
set(CONAN_PKG_LIBS_GLEW_DEBUG libglew32d)
set(CONAN_SYSTEM_LIBS_GLEW_DEBUG )
set(CONAN_FRAMEWORKS_GLEW_DEBUG )
set(CONAN_FRAMEWORKS_FOUND_GLEW_DEBUG "")  # Will be filled later
set(CONAN_DEFINES_GLEW_DEBUG "-DGLEW_STATIC")
set(CONAN_BUILD_MODULES_PATHS_GLEW_DEBUG )
# COMPILE_DEFINITIONS are equal to CONAN_DEFINES without -D, for targets
set(CONAN_COMPILE_DEFINITIONS_GLEW_DEBUG "GLEW_STATIC")

set(CONAN_C_FLAGS_GLEW_DEBUG "")
set(CONAN_CXX_FLAGS_GLEW_DEBUG "")
set(CONAN_SHARED_LINKER_FLAGS_GLEW_DEBUG "")
set(CONAN_EXE_LINKER_FLAGS_GLEW_DEBUG "")

# For modern cmake targets we use the list variables (separated with ;)
set(CONAN_C_FLAGS_GLEW_DEBUG_LIST "")
set(CONAN_CXX_FLAGS_GLEW_DEBUG_LIST "")
set(CONAN_SHARED_LINKER_FLAGS_GLEW_DEBUG_LIST "")
set(CONAN_EXE_LINKER_FLAGS_GLEW_DEBUG_LIST "")

# Apple Frameworks
conan_find_apple_frameworks(CONAN_FRAMEWORKS_FOUND_GLEW_DEBUG "${CONAN_FRAMEWORKS_GLEW_DEBUG}" "_GLEW" "_DEBUG")
# Append to aggregated values variable
set(CONAN_LIBS_GLEW_DEBUG ${CONAN_PKG_LIBS_GLEW_DEBUG} ${CONAN_SYSTEM_LIBS_GLEW_DEBUG} ${CONAN_FRAMEWORKS_FOUND_GLEW_DEBUG})


#################
###  GLFW
#################
set(CONAN_GLFW_ROOT_DEBUG "C:/Users/Woazim/.conan/data/glfw/3.3.7/_/_/package/72e84aac9213a09dfb0f59578ae9423a2eb326e7")
set(CONAN_INCLUDE_DIRS_GLFW_DEBUG "C:/Users/Woazim/.conan/data/glfw/3.3.7/_/_/package/72e84aac9213a09dfb0f59578ae9423a2eb326e7/include")
set(CONAN_LIB_DIRS_GLFW_DEBUG "C:/Users/Woazim/.conan/data/glfw/3.3.7/_/_/package/72e84aac9213a09dfb0f59578ae9423a2eb326e7/lib")
set(CONAN_BIN_DIRS_GLFW_DEBUG )
set(CONAN_RES_DIRS_GLFW_DEBUG )
set(CONAN_SRC_DIRS_GLFW_DEBUG )
set(CONAN_BUILD_DIRS_GLFW_DEBUG "C:/Users/Woazim/.conan/data/glfw/3.3.7/_/_/package/72e84aac9213a09dfb0f59578ae9423a2eb326e7/")
set(CONAN_FRAMEWORK_DIRS_GLFW_DEBUG )
set(CONAN_LIBS_GLFW_DEBUG glfw3)
set(CONAN_PKG_LIBS_GLFW_DEBUG glfw3)
set(CONAN_SYSTEM_LIBS_GLFW_DEBUG gdi32)
set(CONAN_FRAMEWORKS_GLFW_DEBUG )
set(CONAN_FRAMEWORKS_FOUND_GLFW_DEBUG "")  # Will be filled later
set(CONAN_DEFINES_GLFW_DEBUG )
set(CONAN_BUILD_MODULES_PATHS_GLFW_DEBUG )
# COMPILE_DEFINITIONS are equal to CONAN_DEFINES without -D, for targets
set(CONAN_COMPILE_DEFINITIONS_GLFW_DEBUG )

set(CONAN_C_FLAGS_GLFW_DEBUG "")
set(CONAN_CXX_FLAGS_GLFW_DEBUG "")
set(CONAN_SHARED_LINKER_FLAGS_GLFW_DEBUG "")
set(CONAN_EXE_LINKER_FLAGS_GLFW_DEBUG "")

# For modern cmake targets we use the list variables (separated with ;)
set(CONAN_C_FLAGS_GLFW_DEBUG_LIST "")
set(CONAN_CXX_FLAGS_GLFW_DEBUG_LIST "")
set(CONAN_SHARED_LINKER_FLAGS_GLFW_DEBUG_LIST "")
set(CONAN_EXE_LINKER_FLAGS_GLFW_DEBUG_LIST "")

# Apple Frameworks
conan_find_apple_frameworks(CONAN_FRAMEWORKS_FOUND_GLFW_DEBUG "${CONAN_FRAMEWORKS_GLFW_DEBUG}" "_GLFW" "_DEBUG")
# Append to aggregated values variable
set(CONAN_LIBS_GLFW_DEBUG ${CONAN_PKG_LIBS_GLFW_DEBUG} ${CONAN_SYSTEM_LIBS_GLFW_DEBUG} ${CONAN_FRAMEWORKS_FOUND_GLFW_DEBUG})


#################
###  CATCH2
#################
set(CONAN_CATCH2_ROOT_DEBUG "C:/Users/Woazim/.conan/data/catch2/2.13.8/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9")
set(CONAN_INCLUDE_DIRS_CATCH2_DEBUG "C:/Users/Woazim/.conan/data/catch2/2.13.8/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include")
set(CONAN_LIB_DIRS_CATCH2_DEBUG "C:/Users/Woazim/.conan/data/catch2/2.13.8/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib")
set(CONAN_BIN_DIRS_CATCH2_DEBUG )
set(CONAN_RES_DIRS_CATCH2_DEBUG )
set(CONAN_SRC_DIRS_CATCH2_DEBUG )
set(CONAN_BUILD_DIRS_CATCH2_DEBUG "C:/Users/Woazim/.conan/data/catch2/2.13.8/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib/cmake/Catch2")
set(CONAN_FRAMEWORK_DIRS_CATCH2_DEBUG )
set(CONAN_LIBS_CATCH2_DEBUG )
set(CONAN_PKG_LIBS_CATCH2_DEBUG )
set(CONAN_SYSTEM_LIBS_CATCH2_DEBUG )
set(CONAN_FRAMEWORKS_CATCH2_DEBUG )
set(CONAN_FRAMEWORKS_FOUND_CATCH2_DEBUG "")  # Will be filled later
set(CONAN_DEFINES_CATCH2_DEBUG )
set(CONAN_BUILD_MODULES_PATHS_CATCH2_DEBUG )
# COMPILE_DEFINITIONS are equal to CONAN_DEFINES without -D, for targets
set(CONAN_COMPILE_DEFINITIONS_CATCH2_DEBUG )

set(CONAN_C_FLAGS_CATCH2_DEBUG "")
set(CONAN_CXX_FLAGS_CATCH2_DEBUG "")
set(CONAN_SHARED_LINKER_FLAGS_CATCH2_DEBUG "")
set(CONAN_EXE_LINKER_FLAGS_CATCH2_DEBUG "")

# For modern cmake targets we use the list variables (separated with ;)
set(CONAN_C_FLAGS_CATCH2_DEBUG_LIST "")
set(CONAN_CXX_FLAGS_CATCH2_DEBUG_LIST "")
set(CONAN_SHARED_LINKER_FLAGS_CATCH2_DEBUG_LIST "")
set(CONAN_EXE_LINKER_FLAGS_CATCH2_DEBUG_LIST "")

# Apple Frameworks
conan_find_apple_frameworks(CONAN_FRAMEWORKS_FOUND_CATCH2_DEBUG "${CONAN_FRAMEWORKS_CATCH2_DEBUG}" "_CATCH2" "_DEBUG")
# Append to aggregated values variable
set(CONAN_LIBS_CATCH2_DEBUG ${CONAN_PKG_LIBS_CATCH2_DEBUG} ${CONAN_SYSTEM_LIBS_CATCH2_DEBUG} ${CONAN_FRAMEWORKS_FOUND_CATCH2_DEBUG})


#################
###  GLU
#################
set(CONAN_GLU_ROOT_DEBUG "C:/Users/Woazim/.conan/data/glu/system/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9")
set(CONAN_INCLUDE_DIRS_GLU_DEBUG )
set(CONAN_LIB_DIRS_GLU_DEBUG )
set(CONAN_BIN_DIRS_GLU_DEBUG )
set(CONAN_RES_DIRS_GLU_DEBUG )
set(CONAN_SRC_DIRS_GLU_DEBUG )
set(CONAN_BUILD_DIRS_GLU_DEBUG "C:/Users/Woazim/.conan/data/glu/system/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/")
set(CONAN_FRAMEWORK_DIRS_GLU_DEBUG )
set(CONAN_LIBS_GLU_DEBUG )
set(CONAN_PKG_LIBS_GLU_DEBUG )
set(CONAN_SYSTEM_LIBS_GLU_DEBUG Glu32)
set(CONAN_FRAMEWORKS_GLU_DEBUG )
set(CONAN_FRAMEWORKS_FOUND_GLU_DEBUG "")  # Will be filled later
set(CONAN_DEFINES_GLU_DEBUG )
set(CONAN_BUILD_MODULES_PATHS_GLU_DEBUG )
# COMPILE_DEFINITIONS are equal to CONAN_DEFINES without -D, for targets
set(CONAN_COMPILE_DEFINITIONS_GLU_DEBUG )

set(CONAN_C_FLAGS_GLU_DEBUG "")
set(CONAN_CXX_FLAGS_GLU_DEBUG "")
set(CONAN_SHARED_LINKER_FLAGS_GLU_DEBUG "")
set(CONAN_EXE_LINKER_FLAGS_GLU_DEBUG "")

# For modern cmake targets we use the list variables (separated with ;)
set(CONAN_C_FLAGS_GLU_DEBUG_LIST "")
set(CONAN_CXX_FLAGS_GLU_DEBUG_LIST "")
set(CONAN_SHARED_LINKER_FLAGS_GLU_DEBUG_LIST "")
set(CONAN_EXE_LINKER_FLAGS_GLU_DEBUG_LIST "")

# Apple Frameworks
conan_find_apple_frameworks(CONAN_FRAMEWORKS_FOUND_GLU_DEBUG "${CONAN_FRAMEWORKS_GLU_DEBUG}" "_GLU" "_DEBUG")
# Append to aggregated values variable
set(CONAN_LIBS_GLU_DEBUG ${CONAN_PKG_LIBS_GLU_DEBUG} ${CONAN_SYSTEM_LIBS_GLU_DEBUG} ${CONAN_FRAMEWORKS_FOUND_GLU_DEBUG})


#################
###  OPENGL
#################
set(CONAN_OPENGL_ROOT_DEBUG "C:/Users/Woazim/.conan/data/opengl/system/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9")
set(CONAN_INCLUDE_DIRS_OPENGL_DEBUG )
set(CONAN_LIB_DIRS_OPENGL_DEBUG )
set(CONAN_BIN_DIRS_OPENGL_DEBUG )
set(CONAN_RES_DIRS_OPENGL_DEBUG )
set(CONAN_SRC_DIRS_OPENGL_DEBUG )
set(CONAN_BUILD_DIRS_OPENGL_DEBUG "C:/Users/Woazim/.conan/data/opengl/system/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/")
set(CONAN_FRAMEWORK_DIRS_OPENGL_DEBUG )
set(CONAN_LIBS_OPENGL_DEBUG )
set(CONAN_PKG_LIBS_OPENGL_DEBUG )
set(CONAN_SYSTEM_LIBS_OPENGL_DEBUG opengl32)
set(CONAN_FRAMEWORKS_OPENGL_DEBUG )
set(CONAN_FRAMEWORKS_FOUND_OPENGL_DEBUG "")  # Will be filled later
set(CONAN_DEFINES_OPENGL_DEBUG )
set(CONAN_BUILD_MODULES_PATHS_OPENGL_DEBUG )
# COMPILE_DEFINITIONS are equal to CONAN_DEFINES without -D, for targets
set(CONAN_COMPILE_DEFINITIONS_OPENGL_DEBUG )

set(CONAN_C_FLAGS_OPENGL_DEBUG "")
set(CONAN_CXX_FLAGS_OPENGL_DEBUG "")
set(CONAN_SHARED_LINKER_FLAGS_OPENGL_DEBUG "")
set(CONAN_EXE_LINKER_FLAGS_OPENGL_DEBUG "")

# For modern cmake targets we use the list variables (separated with ;)
set(CONAN_C_FLAGS_OPENGL_DEBUG_LIST "")
set(CONAN_CXX_FLAGS_OPENGL_DEBUG_LIST "")
set(CONAN_SHARED_LINKER_FLAGS_OPENGL_DEBUG_LIST "")
set(CONAN_EXE_LINKER_FLAGS_OPENGL_DEBUG_LIST "")

# Apple Frameworks
conan_find_apple_frameworks(CONAN_FRAMEWORKS_FOUND_OPENGL_DEBUG "${CONAN_FRAMEWORKS_OPENGL_DEBUG}" "_OPENGL" "_DEBUG")
# Append to aggregated values variable
set(CONAN_LIBS_OPENGL_DEBUG ${CONAN_PKG_LIBS_OPENGL_DEBUG} ${CONAN_SYSTEM_LIBS_OPENGL_DEBUG} ${CONAN_FRAMEWORKS_FOUND_OPENGL_DEBUG})


### Definition of global aggregated variables ###

set(CONAN_DEPENDENCIES_DEBUG glew glfw catch2 glu opengl)

set(CONAN_INCLUDE_DIRS_DEBUG "C:/Users/Woazim/.conan/data/glew/2.2.0/_/_/package/2cd10aa7b17419a389740c9a9a85afec1178e5cf/include"
			"C:/Users/Woazim/.conan/data/glfw/3.3.7/_/_/package/72e84aac9213a09dfb0f59578ae9423a2eb326e7/include"
			"C:/Users/Woazim/.conan/data/catch2/2.13.8/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include" ${CONAN_INCLUDE_DIRS_DEBUG})
set(CONAN_LIB_DIRS_DEBUG "C:/Users/Woazim/.conan/data/glew/2.2.0/_/_/package/2cd10aa7b17419a389740c9a9a85afec1178e5cf/lib"
			"C:/Users/Woazim/.conan/data/glfw/3.3.7/_/_/package/72e84aac9213a09dfb0f59578ae9423a2eb326e7/lib"
			"C:/Users/Woazim/.conan/data/catch2/2.13.8/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib" ${CONAN_LIB_DIRS_DEBUG})
set(CONAN_BIN_DIRS_DEBUG  ${CONAN_BIN_DIRS_DEBUG})
set(CONAN_RES_DIRS_DEBUG  ${CONAN_RES_DIRS_DEBUG})
set(CONAN_FRAMEWORK_DIRS_DEBUG  ${CONAN_FRAMEWORK_DIRS_DEBUG})
set(CONAN_LIBS_DEBUG libglew32d glfw3 ${CONAN_LIBS_DEBUG})
set(CONAN_PKG_LIBS_DEBUG libglew32d glfw3 ${CONAN_PKG_LIBS_DEBUG})
set(CONAN_SYSTEM_LIBS_DEBUG gdi32 Glu32 opengl32 ${CONAN_SYSTEM_LIBS_DEBUG})
set(CONAN_FRAMEWORKS_DEBUG  ${CONAN_FRAMEWORKS_DEBUG})
set(CONAN_FRAMEWORKS_FOUND_DEBUG "")  # Will be filled later
set(CONAN_DEFINES_DEBUG "-DGLEW_STATIC" ${CONAN_DEFINES_DEBUG})
set(CONAN_BUILD_MODULES_PATHS_DEBUG  ${CONAN_BUILD_MODULES_PATHS_DEBUG})
set(CONAN_CMAKE_MODULE_PATH_DEBUG "C:/Users/Woazim/.conan/data/glew/2.2.0/_/_/package/2cd10aa7b17419a389740c9a9a85afec1178e5cf/"
			"C:/Users/Woazim/.conan/data/glfw/3.3.7/_/_/package/72e84aac9213a09dfb0f59578ae9423a2eb326e7/"
			"C:/Users/Woazim/.conan/data/catch2/2.13.8/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib/cmake/Catch2"
			"C:/Users/Woazim/.conan/data/glu/system/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/"
			"C:/Users/Woazim/.conan/data/opengl/system/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/" ${CONAN_CMAKE_MODULE_PATH_DEBUG})

set(CONAN_CXX_FLAGS_DEBUG " ${CONAN_CXX_FLAGS_DEBUG}")
set(CONAN_SHARED_LINKER_FLAGS_DEBUG " ${CONAN_SHARED_LINKER_FLAGS_DEBUG}")
set(CONAN_EXE_LINKER_FLAGS_DEBUG " ${CONAN_EXE_LINKER_FLAGS_DEBUG}")
set(CONAN_C_FLAGS_DEBUG " ${CONAN_C_FLAGS_DEBUG}")

# Apple Frameworks
conan_find_apple_frameworks(CONAN_FRAMEWORKS_FOUND_DEBUG "${CONAN_FRAMEWORKS_DEBUG}" "" "_DEBUG")
# Append to aggregated values variable: Use CONAN_LIBS instead of CONAN_PKG_LIBS to include user appended vars
set(CONAN_LIBS_DEBUG ${CONAN_LIBS_DEBUG} ${CONAN_SYSTEM_LIBS_DEBUG} ${CONAN_FRAMEWORKS_FOUND_DEBUG})
